# Instructions ----
#' This file follows the format generated by FIMS:::use_testthat_template().
#' Necessary tests include input and output (IO) correctness [IO
#' correctness], edge-case handling [Edge handling], and built-in errors and
#' warnings [Error handling]. See `?FIMS:::use_testthat_template` for more
#' information. Every test should have a @description tag, which can only span
#' one lines, that will be used in the bookdown report of the results from
#' {testthat}. This line can be more than 80 characters.

# {{{ plot_counts_scatterplot }}} ----
## Setup ----
scatterplot_df <- dplyr::tibble(
  model_count = c(10, 1, 5, 0),
  truth_count = c(12, 0, 5, 2)
)

## IO correctness ----
test_that("plot_counts_scatterplot() works with correct inputs", {
  #' @description Test that plot_counts_scatterplot returns a ggplot object.
  p <- plot_counts_scatterplot(scatterplot_df)
  expect_s3_class(p, "ggplot")
  expect_equal(p$labels$x, "Ground Truth Count")
  expect_equal(p$labels$y, "Model Predicted Count")
})

## Error handling ----
test_that("plot_counts_scatterplot() returns correct error messages", {
  #' @description Test that plot_counts_scatterplot() errors if columns are missing.
  expect_error(
    plot_counts_scatterplot(dplyr::tibble(a = 1, b = 2)),
    regexp = "must contain 'model_count' and 'truth_count' columns"
  )
})


# {{{ plot_pr_curve }}} ----
## Setup ----
pr_data <- dplyr::tibble(
  score = c(0.9, 0.8, 0.7, 0.6, 0.5, 0.4, 0.3, 0.2),
  status = c("TP", "TP", "FP", "TP", "FP", "FP", "TP", "FP")
)
pr_data_multi <- dplyr::tibble(
  score = c(0.9, 0.8, 0.7, 0.6, 0.55, 0.45),
  status = c("TP", "FP", "TP", "FP", "TP", "FP"),
  model_identifier = rep(c("Model A", "Model B"), each = 3)
)

## IO correctness ----
test_that("plot_pr_curve() works with correct inputs", {
  #' @description Test that plot_pr_curve() returns a ggplot object for a single model.
  p <- plot_pr_curve(pr_data)
  expect_s3_class(p, "ggplot")
  expect_equal(p$labels$title, "Precision-Recall Curve")

  #' @description Test that plot_pr_curve() handles multiple models correctly.
  p_multi <- plot_pr_curve(pr_data_multi, model_col = model_identifier)
  expect_s3_class(p_multi, "ggplot")
  expect_equal(length(unique(p_multi$data$legend_label)), 2)
})

# {{{ plot_bland_altman }}} ----
## Setup ----
bland_altman_df <- dplyr::tibble(
  model_count = c(10, 1, 5, 4),
  truth_count = c(12, 0, 5, 2)
)

## IO correctness ----
test_that("plot_bland_altman() works with correct inputs", {
  #' @description Test that plot_bland_altman returns a ggplot object.
  p <- plot_bland_altman(bland_altman_df)
  expect_s3_class(p, "ggplot")
  expect_equal(p$labels$x, "Average of Counts")
  expect_equal(p$labels$y, "Difference (Model - Truth)")
})

# {{{ plot_confusion_matrix }}} ----
## Setup ----
cm_metrics <- dplyr::tibble(tp = 10, fp = 2, fn = 3, tn = 85)

## IO correctness ----
test_that("plot_confusion_matrix() works with correct inputs", {
  #' @description Test that plot_confusion_matrix() returns a ggplot object.
  p <- plot_confusion_matrix(cm_metrics, title = "Test CM")
  expect_s3_class(p, "ggplot")
  expect_equal(p$labels$title, "Test CM")

  #' @description Test that plot_confusion_matrix() correctly maps data to the plot.
  p <- plot_confusion_matrix(cm_metrics)
  expect_equal(nrow(p$data), 4)
  expect_equal(p$data$N[p$data$Truth == "Positive" & p$data$Prediction == "Positive"], cm_metrics$tp)
  expect_equal(p$data$N[p$data$Truth == "Positive" & p$data$Prediction == "Negative"], cm_metrics$fn)
})

# {{{ plot_roc_curve }}} ----
## Setup ----
roc_data <- dplyr::tibble(
  score = c(0.9, 0.8, 0.7, 0.6, 0.5, 0.4, 0.3, 0.2),
  status = c("TP", "TP", "FP", "TP", "FP", "FP", "TP", "FP")
)

## IO correctness ----
test_that("plot_roc_curve() works correctly", {
  #' @description Test that plot_roc_curve() returns a ggplot object.
  p <- plot_roc_curve(roc_data, title = "Test ROC")
  expect_s3_class(p, "ggplot")
  expect_equal(p$labels$title, "Test ROC")

  #' @description Test that plot_roc_curve() contains the correct geometric layers.
  p <- plot_roc_curve(roc_data)
  geoms <- sapply(p$layers, function(x) class(x$geom)[1])
  expect_true("GeomLine" %in% geoms)
  expect_true("GeomAbline" %in% geoms)
  expect_true("GeomText" %in% geoms)
})

# {{{ plot_multiclass_confusion_matrix }}} ----
## Setup ----
multi_cm_data <- dplyr::tribble(
  ~Truth,     ~Prediction,          ~n,
  "SpeciesA", "SpeciesA",           10L,
  "SpeciesB", "SpeciesA",           2L,
  "SpeciesA", "FN (No Prediction)", 1L
)

## IO correctness ----
test_that("plot_multiclass_confusion_matrix() returns a ggplot object", {
  #' @description Test that plot_multiclass_confusion_matrix() returns a ggplot object for valid inputs.
  p <- plot_multiclass_confusion_matrix(multi_cm_data, title = "Test Plot")
  expect_s3_class(p, "ggplot")
})

## Error handling ----
test_that("plot_multiclass_confusion_matrix() returns correct error messages", {
  #' @description Test that plot_multiclass_confusion_matrix() throws an error for incorrect columns.
  bad_data <- dplyr::tribble(~True_Species, ~Predicted_Species, ~count, "SpeciesA", "SpeciesA", 10L)
  expect_error(plot_multiclass_confusion_matrix(bad_data))
})

# {{{ plot_performance_by_threshold }}} ----
## Setup ----
perf_summary_df <- dplyr::tibble(
  threshold = rep(seq(0.1, 0.5, 0.1), 2),
  precision = runif(10, 0.5, 1),
  recall = runif(10, 0.5, 1),
  f1_score = runif(10, 0.5, 1),
  model_name = rep(c("Model A", "Model B"), each = 5)
)

## IO correctness ----
test_that("plot_performance_by_threshold() works correctly", {
  #' @description Test that plot_performance_by_threshold() returns a faceted ggplot object.
  p <- plot_performance_by_threshold(perf_summary_df, model_col = model_name)
  expect_s3_class(p, "ggplot")
  expect_true("FacetWrap" %in% class(p$facet))

  #' @description Test that plot_performance_by_threshold() correctly pivots the data for plotting.
  p <- plot_performance_by_threshold(perf_summary_df, model_col = model_name)
  p_data <- ggplot2::ggplot_build(p)$data[[1]]
  expect_true("colour" %in% names(p_data))
  expect_equal(length(unique(p_data$colour)), 3)
})
