# Instructions ----
#' This file follows the format generated by FIMS:::use_testthat_template().
#' Necessary tests include input and output (IO) correctness [IO
#' correctness], edge-case handling [Edge handling], and built-in errors and
#' warnings [Error handling]. See `?FIMS:::use_testthat_template` for more
#' information. Every test should have a @description tag, which can only span
#' one lines, that will be used in the bookdown report of the results from
#' {testthat}. This line can be more than 80 characters.

# {{{ calculate_maxn }}} ----
## Setup ----
maxn_df <- dplyr::tibble(
  video_id = c(rep("v1", 4), rep("v2", 3)),
  image_id = "test_image",
  frame_index = c(1, 1, 2, 2, 1, 1, 1),
  category_name = c("A", "A", "A", "B", "A", "A", "A"),
  model_name = "TestModel",
  annotation_id = 1:7,
  bbox_x = 0, bbox_y = 0, bbox_width = 0, bbox_height = 0, score = 0
)
maxn_obj <- OpticsDetections(
  data = maxn_df,
  source_file = "test.csv",
  ingest_format = "test"
)

## IO correctness ----
test_that("calculate_maxn() works with correct inputs", {
  #' @description Test that calculate_maxn() returns correct MaxN counts for an OpticsDetections object.
  maxn_results <- calculate_maxn(maxn_obj)
  expect_equal(nrow(maxn_results), 3)
  expect_equal(maxn_results$maxn[maxn_results$video_id == "v1" & maxn_results$category_name == "A"], 2)
  expect_equal(maxn_results$maxn[maxn_results$video_id == "v2" & maxn_results$category_name == "A"], 3)
  
  #' @description Test that calculate_maxn() works with grouping variables.
  maxn_grouped <- calculate_maxn(maxn_obj, group_cols = "model_name")
  expect_true("model_name" %in% names(maxn_grouped))
})

# {{{ calculate_frame_abundance }}} ----
## Setup ----
abundance_df <- dplyr::tibble(
  video_id = c(rep("v1", 3)),
  image_id = "test_image",
  frame_index = c(1, 1, 2),
  category_name = c("A", "A", "B"),
  annotation_id = 1:3,
  bbox_x = 0, bbox_y = 0, bbox_width = 0, bbox_height = 0, score = 0
)
abundance_obj <- OpticsDetections(
  data = abundance_df,
  source_file = "test.csv",
  ingest_format = "test"
)

## IO correctness ----
test_that("calculate_frame_abundance() works with correct inputs", {
  #' @description Test that calculate_frame_abundance() returns correct per-frame counts.
  abundance_results <- calculate_frame_abundance(abundance_obj)
  expect_equal(nrow(abundance_results), 2)
  expect_equal(abundance_results$abundance[abundance_results$frame_index == 1], 2)
  expect_equal(abundance_results$abundance[abundance_results$frame_index == 2], 1)
})


# {{{ calculate_density }}} ----
## Setup ----
density_df <- dplyr::tibble(
  site = c("A", "B"),
  count = c(10, 25),
  area_m2 = c(5, 10)
)

## IO correctness ----
test_that("calculate_density() works with correct inputs", {
  #' @description Test that calculate_density() works with a fixed area.
  density_fixed_area <- calculate_density(density_df, count_col = count, area = 50)
  expect_true("density" %in% names(density_fixed_area))
  expect_equal(density_fixed_area$density, c(10/50, 25/50))
  
  #' @description Test that calculate_density() works with an area column.
  density_col_area <- calculate_density(density_df, count_col = count, area_col = area_m2)
  expect_true("density" %in% names(density_col_area))
  expect_equal(density_col_area$density, c(10/5, 25/10))
})

## Error handling ----
test_that("calculate_density() returns correct error messages", {
  #' @description Test that calculate_density() errors when both area and area_col are provided.
  expect_error(
    object = calculate_density(density_df, count_col = count, area = 50, area_col = area_m2),
    regexp = "Please provide 'area' or 'area_col', but not both."
  )
})
