# Instructions ----
#' This file follows the format generated by FIMS:::use_testthat_template().
#' Necessary tests include input and output (IO) correctness [IO
#' correctness], edge-case handling [Edge handling], and built-in errors and
#' warnings [Error handling]. See `?FIMS:::use_testthat_template` for more
#' information. Every test should have a @description tag, which can only span
#' one lines, that will be used in the bookdown report of the results from
#' {testthat}. This line can be more than 80 characters.

# {{{ calculate_binary_metrics }}} ----
## Setup ----
binary_metrics_aligned_data <- dplyr::tibble(
  model_count = c(10, 1, 5, 0, 0),
  truth_count = c(12, 0, 0, 2, 8)
)
binary_metrics_grouped_data <- dplyr::tibble(
  category = c("FishA", "FishA", "FishB"),
  model_count = c(5, 0, 3),
  truth_count = c(0, 2, 4)
)

## IO correctness ----
test_that("calculate_binary_metrics() works with correct inputs", {
  #' @description Test that calculate_binary_metrics() calculates ungrouped metrics correctly.
  metrics <- calculate_binary_metrics(binary_metrics_aligned_data, total_comparisons = 100)
  expect_equal(metrics$tp, 1)
  expect_equal(metrics$fp, 2)
  expect_equal(metrics$fn, 2)
  expect_equal(metrics$tn, 95)
  
  #' @description Test that calculate_binary_metrics() calculates grouped metrics correctly.
  metrics_grouped <- calculate_binary_metrics(binary_metrics_grouped_data, group_vars = "category")
  fish_a_metrics <- metrics_grouped[metrics_grouped$category == "FishA", ]
  fish_b_metrics <- metrics_grouped[metrics_grouped$category == "FishB", ]
  expect_equal(fish_a_metrics$fp, 1)
  expect_equal(fish_b_metrics$tp, 1)
})

# {{{ summarize_performance_by_threshold }}} ----
## Setup ----
model_dets_df <- dplyr::tibble(
  video_id = "v1", image_id = "img1", frame_index = c(1, 1, 2),
  annotation_id = 1:3, category_name = c("FishA", "FishA", "FishB"),
  score = c(0.95, 0.85, 0.82), bbox_x = 0, bbox_y = 0, bbox_width = 0, bbox_height = 0
)
truth_dets_df <- dplyr::tibble(
  video_id = "v1", image_id = "img1", frame_index = c(1, 3),
  annotation_id = 4:5, category_name = c("FishA", "FishC"),
  score = 1.0, bbox_x = 0, bbox_y = 0, bbox_width = 0, bbox_height = 0
)
model_detections_perf <- OpticsDetections(model_dets_df, "model.csv", "test")
truth_detections_perf <- OpticsDetections(truth_dets_df, "truth.csv", "test")

## IO correctness ----
test_that("summarize_performance_by_threshold() works with correct inputs", {
  #' @description Test that summarize_performance_by_threshold() returns correct metrics across thresholds.
  summary_df <- summarize_performance_by_threshold(
    model_detections = model_detections_perf,
    truth_detections = truth_detections_perf,
    by = c("video_id", "category_name"),
    thresholds = c(0.8, 0.9)
  )
  expect_equal(nrow(summary_df), 2)
  metrics_at_08 <- summary_df[summary_df$threshold == 0.8, ]
  expect_equal(metrics_at_08$tp, 1)
  expect_equal(metrics_at_08$fp, 1)
  expect_equal(metrics_at_08$fn, 1)
})

# {{{ classify_detections }}} ----
## Setup ----
raw_classify_df <- dplyr::tibble(
  detection_id = 1:5,
  score = c(0.9, 0.8, 0.7, 0.6, 0.5),
  category = "seal"
)
validated_classify_df <- dplyr::tibble(
  detection_id = c(1, 3, 5)
)

## IO correctness ----
test_that("classify_detections() works with correct inputs", {
  #' @description Test that classify_detections() correctly classifies detections as TP or FP.
  classified <- classify_detections(raw_classify_df, validated_classify_df, detection_id = detection_id)
  expect_equal(nrow(classified), 5)
  expect_true("status" %in% names(classified))
  expect_equal(sort(classified$detection_id[classified$status == "TP"]), c(1, 3, 5))
  expect_equal(sort(classified$detection_id[classified$status == "FP"]), c(2, 4))
})

## Error handling ----
test_that("classify_detections() returns correct error messages", {
  #' @description Test that classify_detections() errors when the ID column is missing.
  expect_error(
    classify_detections(raw_classify_df, validated_classify_df, detection_id = wrong_id),
    "must exist in both data frames"
  )
})
