# Instructions ----
#' This file follows the format generated by FIMS:::use_testthat_template().
#' Necessary tests include input and output (IO) correctness [IO
#' correctness], edge-case handling [Edge handling], and built-in errors and
#' warnings [Error handling]. See `?FIMS:::use_testthat_template` for more
#' information. Every test should have a @description tag, which can only span
#' one lines, that will be used in the bookdown report of the results from
#' {testthat}. This line can be more than 80 characters.

# {{{ align_counts }}} ----
## Setup ----
model_df <- dplyr::tibble(
  video_id = c("v1", "v1", "v2"),
  category_name = c("FishA", "FishB", "FishA"),
  model_maxn = c(10, 1, 5)
)
truth_df <- dplyr::tibble(
  video_id = c("v1", "v1", "v3"),
  category_name = c("FishA", "FishC", "FishA"),
  truth_maxn = c(12, 2, 8)
)

## IO correctness ----
test_that("align_counts() works with correct inputs", {
  #' @description Test that align_counts() correctly joins model and truth data frames.
  aligned <- align_counts(
    model_counts = model_df,
    truth_counts = truth_df,
    by = c("video_id", "category_name"),
    model_col = model_maxn,
    truth_col = truth_maxn
  )
  
  expect_equal(nrow(aligned), 5)
  expect_true(all(c("model_count", "truth_count") %in% names(aligned)))
  
  # Check a match
  expect_equal(aligned$model_count[aligned$video_id == "v1" & aligned$category_name == "FishA"], 10)
  expect_equal(aligned$truth_count[aligned$video_id == "v1" & aligned$category_name == "FishA"], 12)
  
  #' @description Test that align_counts() correctly identifies false positives.
  aligned <- align_counts(
    model_counts = model_df,
    truth_counts = truth_df,
    by = c("video_id", "category_name"),
    model_col = model_maxn,
    truth_col = truth_maxn
  )
  expect_equal(aligned$model_count[aligned$video_id == "v1" & aligned$category_name == "FishB"], 1)
  expect_equal(aligned$truth_count[aligned$video_id == "v1" & aligned$category_name == "FishB"], 0)
  
  #' @description Test that align_counts() correctly identifies false negatives.
  aligned <- align_counts(
    model_counts = model_df,
    truth_counts = truth_df,
    by = c("video_id", "category_name"),
    model_col = model_maxn,
    truth_col = truth_maxn
  )
  expect_equal(aligned$model_count[aligned$video_id == "v1" & aligned$category_name == "FishC"], 0)
  expect_equal(aligned$truth_count[aligned$video_id == "v1" & aligned$category_name == "FishC"], 2)
})
