# Instructions ----
#' This file follows the format generated by FIMS:::use_testthat_template().
#' Necessary tests include input and output (IO) correctness [IO
#' correctness], edge-case handling [Edge handling], and built-in errors and
#' warnings [Error handling]. See `?FIMS:::use_testthat_template` for more
#' information. Every test should have a @description tag, which can only span
#' one lines, that will be used in the bookdown report of the results from
#' {testthat}. This line can be more than 80 characters.

# {{{ calculate_binary_metrics }}} ----
## Setup ----
binary_metrics_aligned_data <- dplyr::tibble(
  model_count = c(10, 1, 5, 0, 0),
  truth_count = c(12, 0, 0, 2, 8)
)
binary_metrics_grouped_data <- dplyr::tibble(
  category = c("FishA", "FishA", "FishB"),
  model_count = c(5, 0, 3),
  truth_count = c(0, 2, 4)
)

## IO correctness ----
test_that("calculate_binary_metrics() works with correct inputs", {
  #' @description Test that calculate_binary_metrics() calculates ungrouped metrics correctly.
  metrics <- calculate_binary_metrics(binary_metrics_aligned_data, total_comparisons = 100)
  expect_equal(metrics$tp, 1)
  expect_equal(metrics$fp, 2)
  expect_equal(metrics$fn, 2)
  expect_equal(metrics$tn, 95)
  
  #' @description Test that calculate_binary_metrics() calculates grouped metrics correctly.
  metrics_grouped <- calculate_binary_metrics(binary_metrics_grouped_data, group_vars = "category")
  fish_a_metrics <- metrics_grouped[metrics_grouped$category == "FishA", ]
  fish_b_metrics <- metrics_grouped[metrics_grouped$category == "FishB", ]
  expect_equal(fish_a_metrics$fp, 1)
  expect_equal(fish_b_metrics$tp, 1)
})

# {{{ summarize_performance_by_threshold }}} ----
## Setup ----
model_dets_df <- dplyr::tibble(
  video_id = "v1", image_id = "img1", frame_index = c(1, 1, 2),
  annotation_id = 1:3, category_name = c("FishA", "FishA", "FishB"),
  score = c(0.95, 0.85, 0.82), bbox_x = 0, bbox_y = 0, bbox_width = 0, bbox_height = 0
)
truth_dets_df <- dplyr::tibble(
  video_id = "v1", image_id = "img1", frame_index = c(1, 3),
  annotation_id = 4:5, category_name = c("FishA", "FishC"),
  score = 1.0, bbox_x = 0, bbox_y = 0, bbox_width = 0, bbox_height = 0
)
model_detections_perf <- OpticsDetections(model_dets_df, "model.csv", "test")
truth_detections_perf <- OpticsDetections(truth_dets_df, "truth.csv", "test")

## IO correctness ----
test_that("summarize_performance_by_threshold() works with correct inputs", {
  #' @description Test that summarize_performance_by_threshold() returns correct metrics across thresholds.
  summary_df <- summarize_performance_by_threshold(
    model_detections = model_detections_perf,
    truth_detections = truth_detections_perf,
    by = c("video_id", "category_name"),
    thresholds = c(0.8, 0.9)
  )
  expect_equal(nrow(summary_df), 2)
  metrics_at_08 <- summary_df[summary_df$threshold == 0.8, ]
  expect_equal(metrics_at_08$tp, 1)
  expect_equal(metrics_at_08$fp, 1)
  expect_equal(metrics_at_08$fn, 1)
})

test_that("summarize_performance_by_threshold() uses grouped confidence thresholds by default", {
  #' @description Test that summarize_performance_by_threshold() defaults to legacy grouped confidence thresholds.
  summary_df <- summarize_performance_by_threshold(
    model_detections = model_detections_perf,
    truth_detections = truth_detections_perf,
    by = c("video_id", "category_name")
  )

  expect_equal(summary_df$threshold, c(seq(0.1, 0.9, by = 0.1), 0.95))
})

# {{{ calculate_scalpred_metrics }}} ----
test_that("calculate_scalpred_metrics() computes threshold metrics for OpticsDetections", {
  #' @description Test that ScalPred metrics return expected TP/FP/FN and PR/F1 values.
  metrics_df <- calculate_scalpred_metrics(
    model_detections = model_detections_perf,
    truth_detections = truth_detections_perf,
    by = c("video_id", "category_name"),
    thresholds = c(0.8, 0.9)
  )

  expect_true(all(c("threshold", "tp", "fp", "fn", "precision", "recall", "f1_score") %in% names(metrics_df)))
  expect_equal(nrow(metrics_df), 2)

  metrics_08 <- metrics_df[metrics_df$threshold == 0.8, ]
  expect_equal(metrics_08$tp, 1)
  expect_equal(metrics_08$fp, 1)
  expect_equal(metrics_08$fn, 1)
  expect_equal(metrics_08$precision, 0.5)
  expect_equal(metrics_08$recall, 0.5)
  expect_equal(metrics_08$f1_score, 0.5)
})

test_that("calculate_scalpred_metrics() uses grouped confidence thresholds by default", {
  #' @description Test that ScalPred metrics default to legacy grouped confidence thresholds.
  metrics_df <- calculate_scalpred_metrics(
    model_detections = model_detections_perf,
    truth_detections = truth_detections_perf,
    by = c("video_id", "category_name")
  )

  expect_equal(metrics_df$threshold, c(seq(0.1, 0.9, by = 0.1), 0.95))
})

# {{{ classify_detections }}} ----
## Setup ----
raw_classify_df <- dplyr::tibble(
  detection_id = 1:5,
  score = c(0.9, 0.8, 0.7, 0.6, 0.5),
  category = "seal"
)
validated_classify_df <- dplyr::tibble(
  detection_id = c(1, 3, 5)
)

## IO correctness ----
test_that("classify_detections() works with correct inputs", {
  #' @description Test that classify_detections() correctly classifies detections as TP or FP.
  classified <- classify_detections(raw_classify_df, validated_classify_df, detection_id = detection_id)
  expect_equal(nrow(classified), 5)
  expect_true("status" %in% names(classified))
  expect_equal(sort(classified$detection_id[classified$status == "TP"]), c(1, 3, 5))
  expect_equal(sort(classified$detection_id[classified$status == "FP"]), c(2, 4))
})

## Error handling ----
test_that("classify_detections() returns correct error messages", {
  #' @description Test that classify_detections() errors when the ID column is missing.
  expect_error(
    classify_detections(raw_classify_df, validated_classify_df, detection_id = wrong_id),
    "must exist in both data frames"
  )
})

# {{{ get_disagreement_report }}} ----
## Setup ----
disagreement_df <- dplyr::tibble(
  site = c("A", "A", "B", "C", "C", "D"),
  species = c("cod", "haddock", "cod", "pollock", "cusk", "cod"),
  model_count = c(1, 1, 0, 5, 0, 1),
  truth_count = c(0, 1, 1, 5, 1, 0)
)
# Summary of disagreements:
# (A, cod): 1 FP
# (B, cod): 1 FN
# (C, cusk): 1 FN
# (D, cod): 1 FP (total disagreement 2 for species cod)

## IO correctness ----
test_that("get_disagreement_report() works with correct inputs", {
  #' @description Test that get_disagreement_report() correctly summarizes disagreements.
  report <- get_disagreement_report(disagreement_df, group_vars = c("site", "species"))
  
  # remove rows with no disagreement
  report <- report[report$total_disagreement > 0, ]
  
  expect_equal(nrow(report), 4)
  expect_true(all(report$total_disagreement == 1))
  expect_equal(sum(report$false_positives), 2)
  expect_equal(sum(report$false_negatives), 2)
  
  #' @description Test that get_disagreement_report() respects the top_n parameter.
  report_top2 <- get_disagreement_report(disagreement_df, group_vars = c("site", "species"), top_n = 2)
  report_top2 <- report_top2[report_top2$total_disagreement > 0, ]
  expect_equal(nrow(report_top2), 2)
})

# {{{ analyze_reviewer_effort }}} ----
## Setup ----
raw_effort_df <- dplyr::tibble(
  TrackID = c(1, 2, 3, 4, 5),
  Species = c("cod", "cod", "haddock", "cod", "pollock"),
  video_id = "v1"
)

validated_effort_df <- dplyr::tibble(
  TrackID = c(1, 3, 5, 6),
  Species = c("cod", "pollock", "pollock", "cusk"),
  video_id = "v1"
)

## IO correctness ----
test_that("analyze_reviewer_effort() works with correct inputs", {
  #' @description Test that analyze_reviewer_effort() correctly analyzes effort metrics.
  effort_summary <- analyze_reviewer_effort(raw_effort_df, validated_effort_df, group_vars = "video_id")
  
  expect_equal(nrow(effort_summary), 1)
  expect_equal(effort_summary$n_reclassified, 1)
  expect_equal(effort_summary$n_raw, 5)
  expect_equal(effort_summary$n_validated, 4)
  expect_equal(effort_summary$n_deleted, 1) # 5 raw - 4 validated
  expect_equal(effort_summary$avg_raw_per_validated, 5 / 4)
})

## Error handling ----
test_that("analyze_reviewer_effort() returns correct error messages", {
  #' @description Test that analyze_reviewer_effort() errors if required columns are missing.
  expect_error(
    analyze_reviewer_effort(dplyr::select(raw_effort_df, -TrackID), validated_effort_df),
    "Both data frames must contain 'TrackID' and 'Species' columns."
  )
  
  #' @description Test that analyze_reviewer_effort() errors if group_vars are missing.
  expect_error(
    analyze_reviewer_effort(raw_effort_df, validated_effort_df, group_vars = "missing_col"),
    "All group_vars must be column names in both raw_df and validated_df."
  )
})

# {{{ calculate_confusion_matrix }}} ----
## Setup ----
conf_matrix_df <- dplyr::tibble(
  video_id = "v1",
  category_name = c("cod", "haddock", "pollock", "cusk"),
  model_count = c(1, 1, 0, 0),
  truth_count = c(1, 0, 1, 1)
)

## IO correctness ----
test_that("calculate_confusion_matrix() works with correct inputs", {
  #' @description Test that the fixed calculate_confusion_matrix() correctly calculates the matrix.
  conf_matrix <- calculate_confusion_matrix(
    conf_matrix_df, 
    group_vars = "video_id", 
    species_col = category_name
  )
  
  # Expected: 1 TP (cod), 1 FP (haddock), 2 FN (pollock, cusk)
  expect_equal(nrow(conf_matrix), 4)
  
  tp_row <- conf_matrix[conf_matrix$Truth == "cod",]
  expect_equal(tp_row$Prediction, "cod")
  expect_equal(tp_row$n, 1)
  
  fp_row <- conf_matrix[conf_matrix$Truth == "FP (No Truth)",]
  expect_equal(fp_row$Prediction, "haddock")
  expect_equal(fp_row$n, 1)
  
  fn_rows <- conf_matrix[conf_matrix$Prediction == "FN (No Prediction)",]
  expect_equal(nrow(fn_rows), 2)
  expect_true(all(c("pollock", "cusk") %in% fn_rows$Truth))
})
