# Instructions ----
#' This file follows the format generated by FIMS:::use_testthat_template().
#' Necessary tests include input and output (IO) correctness [IO
#' correctness], edge-case handling [Edge handling], and built-in errors and
#' warnings [Error handling]. See `?FIMS:::use_testthat_template` for more
#' information. Every test should have a @description tag, which can only span
#' one lines, that will be used in the bookdown report of the results from
#' {testthat}. This line can be more than 80 characters.

# {{{ align_counts }}} ----
## Setup ----
# Load or prepare any necessary data for testing
model_df <- dplyr::tibble(
  video_id = c("v1", "v1", "v2"),
  category_name = c("FishA", "FishB", "FishA"),
  score = c(0.9, 0.8, 0.7),
  model_maxn = c(10, 1, 5)
)
truth_df <- dplyr::tibble(
  video_id = c("v1", "v1", "v3"),
  category_name = c("FishA", "FishC", "FishA"),
  truth_maxn = c(12, 2, 8)
)

expected_aligned_df <- dplyr::tribble(
  ~video_id, ~category_name, ~score, ~model_count, ~truth_count,
  "v1", "FishA", 0.9, 10, 12,
  "v1", "FishB", 0.8, 1, 0,
  "v2", "FishA", 0.7, 5, 0,
  "v1", "FishC", NA_real_, 0, 2,
  "v3", "FishA", NA_real_, 0, 8
) %>% dplyr::arrange(video_id, category_name, score)


## IO correctness ----
test_that("align_counts() works with correct inputs", {
  #' @description Test that align_counts() returns a correctly joined and filled tibble.
  result <- align_counts(
    model_counts = model_df,
    truth_counts = truth_df,
    by = c("video_id", "category_name"),
    model_col = model_maxn,
    truth_col = truth_maxn
  ) %>% dplyr::arrange(video_id, category_name, score)

  expect_equal(
    object = result,
    expected = expected_aligned_df
  )
})

## Edge handling ----
test_that("align_counts() returns correct outputs for edge cases", {
  #' @description Test that align_counts() handles empty data frames correctly.
  empty_model <- dplyr::tibble(video_id = character(), category_name = character(), score = numeric(), model_maxn = numeric())
  empty_truth <- dplyr::tibble(video_id = character(), category_name = character(), truth_maxn = numeric())

  expect_equal(
    object = align_counts(empty_model, truth_df, by = c("video_id", "category_name"), model_col=model_maxn, truth_col=truth_maxn) %>% nrow(),
    expected = 3
  )
  expect_equal(
    object = align_counts(model_df, empty_truth, by = c("video_id", "category_name"), model_col=model_maxn, truth_col=truth_maxn) %>% nrow(),
    expected = 3
  )
  expect_equal(
    object = align_counts(empty_model, empty_truth, by = c("video_id", "category_name"), model_col=model_maxn, truth_col=truth_maxn) %>% nrow(),
    expected = 0
  )
})

test_that("align_counts() keeps a plain score column when score is not a join key", {
  #' @description Test that align_counts() coalesces score columns after joining.
  truth_with_score <- truth_df %>%
    dplyr::mutate(score = c(0.95, 0.85, 0.75))

  result <- align_counts(
    model_counts = model_df,
    truth_counts = truth_with_score,
    by = c("video_id", "category_name"),
    model_col = model_maxn,
    truth_col = truth_maxn
  )

  expect_true("score" %in% names(result))
  expect_false(any(c("score.x", "score.y") %in% names(result)))
})

## Error handling ----
# No specific errors are built into align_counts beyond what dplyr::full_join provides.
# Therefore, this section is intentionally left blank.
