#' Read and Flatten a KWCOCO JSON file
#'
#' Ingests a KWCOCO-formatted JSON file and converts it into a standardized
#' tibble where each row represents a single object detection.
#'
#' @param file_path The full path to the KWCOCO JSON file.
#' @return A `tibble` containing the flattened annotation data, conforming to
#'   the package's internal standard schema. Returns an empty tibble if the
#'   file is invalid, cannot be parsed, or contains no annotations.
#' @export
#' @importFrom jsonlite fromJSON
#' @importFrom dplyr tibble inner_join select any_of bind_rows bind_cols rename
#' @importFrom tidyr hoist
#' @examples
#' \dontrun{
#'   # Create a dummy KWCOCO file for demonstration
#'   dummy_kwcoco <- list(
#'     videos = list(list(id = 1, name = "video_1")),
#'     images = list(
#'       list(id = 101, video_id = 1, file_name = "frame_001.jpg", frame_index = 1),
#'       list(id = 102, video_id = 1, file_name = "frame_002.jpg", frame_index = 2)
#'     ),
#'     annotations = list(
#'       list(id = 1, image_id = 101, category_id = 1, track_id = 1,
#'            bbox = c(10, 20, 30, 40), score = 0.95, area = 1200)
#'     ),
#'     categories = list(list(id = 1, name = "Gadus morhua"))
#'   )
#'   json_path <- tempfile(fileext = ".json")
#'   jsonlite::write_json(dummy_kwcoco, json_path, auto_unbox = TRUE)
#'
#'   # Ingest the file
#'   detections_df <- read_kwcoco(json_path)
#'   print(detections_df)
#'
#'   # Clean up
#'   unlink(json_path)
#' }
read_kwcoco <- function(file_path) {
#' @import dplyr

  # --- 1. Input Validation and Reading ---
  if (!file.exists(file_path)) {
    warning("File does not exist: ", file_path)
    return(dplyr::tibble())
  }

  kwcoco_data <- tryCatch({
    jsonlite::fromJSON(file_path, simplifyDataFrame = FALSE)
  }, error = function(e) {
    warning("Failed to parse JSON file: ", file_path, " - Error: ", e$message)
    return(NULL)
  })

  if (is.null(kwcoco_data) || length(kwcoco_data$annotations) == 0) {
    warning("KWCOCO file is empty or contains no annotations: ", basename(file_path))
    return(dplyr::tibble())
  }

  # --- 2. Create Lookup Tables ---
  images_df <- dplyr::bind_rows(kwcoco_data$images)
  categories_df <- dplyr::bind_rows(kwcoco_data$categories)
  videos_df <- dplyr::bind_rows(kwcoco_data$videos)

  # --- 3. Process Annotations ---
  # Explicitly handle the bbox list to avoid auto-unnesting issues.
  # 1. Extract all annotations *except* for the bounding box.
  annotations_df <- dplyr::bind_rows(lapply(kwcoco_data$annotations, function(x) x[names(x) != "bbox"]))

  # 2. Extract the bbox list, convert to a matrix, then a tibble.
  bbox_list <- lapply(kwcoco_data$annotations, `[[`, "bbox")
  bbox_df <- as.data.frame(do.call(rbind, bbox_list))
  names(bbox_df) <- c("bbox_1", "bbox_2", "bbox_3", "bbox_4")

  # 3. Combine them back together.
  annotations_df <- dplyr::bind_cols(annotations_df, bbox_df)

  # --- 4. Join and Standardize ---
  flat_df <- suppressMessages({
    annotations_df %>%
      dplyr::inner_join(images_df, by = c("image_id" = "id"), suffix = c("_ann", "_img")) %>%
      dplyr::inner_join(categories_df, by = c("category_id" = "id"), suffix = c("", "_cat")) %>%
      dplyr::inner_join(videos_df, by = c("video_id" = "id"), suffix = c("_img", "_vid"))
  })

  # Rename to the internal standard schema
  standardized_df <- flat_df %>%
    # Rename columns to our standard before selecting, to handle dplyr's suffixes
    # First, remove original id columns to prevent name clashes
    dplyr::select(-image_id, -video_id) %>%
    dplyr::rename(
      annotation_id = "id",
      category_name = "name_img",
      video_id = "name_vid",
      image_id = "file_name",
      bbox_x = "bbox_1",
      bbox_y = "bbox_2",
      bbox_width = "bbox_3",
      bbox_height = "bbox_4"
    ) %>%
    dplyr::select(dplyr::any_of(c(
      "video_id", "image_id", "frame_index", "annotation_id", "track_id",
      "category_id", "category_name", "bbox_x", "bbox_y",
      "bbox_width", "bbox_height", "score", "area"
    )))

  return(standardized_df)
}

#' Read and Standardize a VIAME-style CSV File
#'
#' Ingests a CSV file generated by the VIAME toolkit, which typically contains
#' object or track detections. It skips the standard 2-line header and maps
#' the columns to the package's internal standard schema.
#'
#' @param file_path The full path to the VIAME CSV file.
#' @param video_id An optional character string to assign as the video ID.
#'   If `NULL` (the default), the video ID is derived from the input file's name.
#' @return A `tibble` containing the standardized detection data. Returns an
#'   empty tibble if the file is empty or cannot be read.
#' @export
#' @importFrom readr read_csv cols
#' @import readr
#' @importFrom dplyr tibble rename mutate select across
#' @importFrom tools file_path_sans_ext
read_viame_csv <- function(file_path, video_id = NULL) {

  # --- 1. Input Validation ---
  if (!file.exists(file_path)) {
    warning("File does not exist: ", file_path)
    return(dplyr::tibble())
  }

  # --- 2. Read Data ---
  raw_df <- tryCatch({
    readr::read_csv(
      file_path,
      skip = 2,
      col_names = FALSE,
      col_types = readr::cols(.default = "c"),
      show_col_types = FALSE
    )
  }, error = function(e) {
    warning("Failed to read CSV file: ", file_path, " - Error: ", e$message)
    return(NULL)
  })

  if (is.null(raw_df) || nrow(raw_df) == 0) {
    warning("VIAME CSV file is empty or could not be read: ", basename(file_path))
    return(dplyr::tibble())
  }

  # --- 3. Assign Column Names and Standardize ---
  viame_names <- c(
    "TrackID", "VidIdent", "UniqFrame", "TL_X", "TL_Y", "BR_X", "BR_Y",
    "DetLen_Conf", "Tar_Len", "SP", "CP"
  )
  names(raw_df)[1:min(ncol(raw_df), length(viame_names))] <- viame_names[1:min(ncol(raw_df), length(viame_names))]

  if (is.null(video_id)) {
    video_id <- tools::file_path_sans_ext(basename(file_path))
  }

  standardized_df <- raw_df %>%
    dplyr::mutate(
      video_id = !!video_id,
      image_id = paste0(video_id, "_frame_", .data$UniqFrame),
      bbox_width = as.numeric(.data$BR_X) - as.numeric(.data$TL_X),
      bbox_height = as.numeric(.data$BR_Y) - as.numeric(.data$TL_Y)
    ) %>%
    dplyr::rename(
      annotation_id = "TrackID",
      frame_index = "UniqFrame",
      category_name = "SP",
      score = "DetLen_Conf",
      bbox_x = "TL_X",
      bbox_y = "TL_Y"
    ) %>%
    dplyr::mutate(dplyr::across(
      c(frame_index, bbox_x, bbox_y, bbox_width, bbox_height, score),
      ~as.numeric(as.character(.))
    )) %>%
    dplyr::select(
      dplyr::any_of(c(
        "video_id", "image_id", "frame_index", "annotation_id", "category_name",
        "bbox_x", "bbox_y", "bbox_width", "bbox_height", "score"
      ))
    )

  return(standardized_df)
}
